server.port: 8092

eureka.client.service-url.defaultZone : http://localhost:8090/eureka
spring:
    application:
        name: gatteway-server
    cloud: 
       gateway: 
          routes:
            - id :  product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/** 
              filters:
               - StripPrefix=2
               - Ejemplo= mensaje personalizado,usuario ,wspereira
#               - name: Ejemplo
#                 args: 
#                    - mensaje: mensaje personalizado
#                    - cookieValue: wspereira 
#                    - cookieName: usuario
            - id :  item-service
              uri: lb://item-service
              predicates:
                - Path=/api/items/**
              filters:
               - StripPrefix= 2 
               
                
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 60000          
        