spring:
  config:
    use-legacy-processing: true      
    import: "optional:configserver:"
  application:
    name: product-service
  

server.port: 8020
eureka:
  client.service-url.defaultZone: http://localhost:8090/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file: ./logs/gestion-authenticacion.log
  level:
    com.wspereira.udemy.microservice.productservice: DEBUG
    org.springframewor.jdbc.core.JdbcTemplate: DEBUG
    org.springframewor.jdbc.core.StatementCreatorUtils: TRACE
