
spring:
  application:
    name: item-service
  #config.import: optional:configserver  
server.port: ${PORT:0}
eureka:
    client.service-url.defaultZone : http://localhost:8090/eureka
    instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}    

resilience4j:
    circuitbreaker:
        configs:
            defecto:
                sliding-window-size: 6
                failure-rate-threshold: 50
                wait-duration-in-open-state: 20s
                permitted-number-of-calls-in-half-open-state: 4
        instances:
            items: 
             base-config: defecto
                
                
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000