server.port: ${PORT:0}
spring:    
    spring:
    zipkin:
      base-url: http://localhost9411
      sender:
       type: rabbit
      service:
       name: ${spring.application.name}  
    sleuth:
     sampler:
      probability: 1 
    #nombre de la aplicacion con que se registrara en eureka
    application:
        name: user-service
eureka:
    #donde esta ubicado nuestro servicio eureka para registrarse y descubrimiento
    client.service-url.defaultZone : http://localhost:8090/eureka
    #creando una intancia randon en eureka por cada instancia levantada
    instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}    
   

logging:
    file: ./logs/gestion-authenticacion.log
    level:
        com.wspereira.udemy.microservice.productservice: DEBUG
        org:
            springframewor.jdbc.core:
                                 JdbcTemplate: DEBUG
                                 StatementCreatorUtils: TRACE  
            hibernate:SQL: debug
